pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Praveen Penumaka
url: http://praveenpenumaka.github.io
description: A fantastic blog that is fantastic.
twitter: praveenpenumaka
github: praveenpenumaka
gravatar_url: https://s.gravatar.com/avatar/5c61a0287b2663fbe0934b82cd802542